"""add unique constraint to system_instructions

Revision ID: 4ed950d61fa3
Revises: 7ee0f0e4f70d
Create Date: 2025-07-28 19:42:18.556726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed950d61fa3'
down_revision: Union[str, Sequence[str], None] = '7ee0f0e4f70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_role_type', 'system_instructions', ['role', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_role_type', 'system_instructions', type_='unique')
    # ### end Alembic commands ###
