CLARITY_GRADER_SYSTEM_INSTRUCTIONS = """"""
SPECIFICITY_GRADER_SYSTEM_INSTRUCTIONS = """"""
COMPLEXITY_GRADER_SYSTEM_INSTRUCTIONS = """"""
COMPLETENESS_GRADER_SYSTEM_INSTRUCTIONS = """"""
CONSISTENCY_GRADER_SYSTEM_INSTRUCTIONS = """"""

MASTER_GRADER_SYSTEM_INSTRUCTIONS = """"""